name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd ~/fastapi-book-project

            # Pull latest changes
            git pull origin main

            # Activate virtual environment and install dependencies
            source venv/bin/activate
            pip install -r requirements.txt

            # Check if a PID file exists
            if [ -f app.pid ]; then
              # Get the PID from the file
              OLD_PID=$(cat app.pid)
              if ps -p $OLD_PID > /dev/null; then
                echo "Stopping existing process..."
                kill $OLD_PID
                # Wait for process to stop gracefully
                sleep 5
                # Force kill if still running
                if ps -p $OLD_PID > /dev/null; then
                  kill -9 $OLD_PID
                fi
              fi
            fi

            # Start the application with nohup and save PID
            echo "Starting new process..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 & echo $! > app.pid

            # Wait a moment and check if process is running
            sleep 5
            if ps -p $(cat app.pid) > /dev/null; then
              echo "Deployment successful!"
            else
              echo "Deployment failed! Check app.log for details."
              exit 1
            fi
