name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: cd ~/fastapi-book-project && pkill -f "uvicorn main:app" || true && git pull origin main && source venv/bin/activate && pip install -r requirements.txt && nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 & && sleep 5 && ps aux | grep "uvicorn main:app"
